module.exports = (key) => {

  return [`what wine goes with ${key}?`,
    `what's a good wine for ${key}?`,
    `what’s good with ${key}?`,
    `what’s good for ${key}?`,
    `i need a wine to go with ${key}`,
    `what’s the best wine for ${key}?`,
    `i need a match for ${key}`,
    `i need to pair with ${key}`,
    `give me a wine for ${key}`,
    `i want a bottle that goes with ${key}`,
    `what’s your favorite wine for ${key}?`,
    `i'm looking for a wine to go with ${key}`,
    `i'm looking for a wine that goes with ${key}`,
    `i'm looking for something to go with ${key}`,
    `i’m looking for something that goes with ${key}`,
    `i'm looking for something for ${key}`,
    `what do you recommend for ${key}?`,
    `what do you suggest for ${key}?`,
    `what do you think goes with ${key}?`,
    `what would you pair with ${key}?`,
    `what goes with ${key}?`,
    `what pairs with ${key}?`,
    `what’s best with ${key}?`,
    `what's a match for ${key}?`,
    `i'm having ${key}`,
    `i'm having ${key} for lunch`,
    `i'm having ${key} for dinner`,
    `i'm making ${key}`,
    `i'm cooking ${key}`,
    `i'm eating ${key}`,
    `we’re having ${key}`,
    `for ${key} what do you recommend?`,
    `i'm dining on ${key}`,
    `i'm at a ${key} restaurant`,
    `what do you suggest if i'm having ${key}?`,
    `what about ${key}?`,
    `i’m planning a ${key}`,
    `what do you think about ${key}?`,
    `what’s the best wine for ${key}?`]
}
