module.exports =  {
  bold: {
    ResidualSugar: 1,
    Body: 4,
    Acidity: 3,
    Oak: 3,
    Intensity: 5,
    Tannin: 3,
    Fruit: 4,
  },
  buttery: {
    ResidualSugar: 1,
    Body: 4,
    Acidity: 2,
    Oak: 4,
    Intensity: 4,
    Tannin: 1,
    Fruit: 3,
  },
  dry: {
    ResidualSugar: 1,
    Body: 3,
    Acidity: 4,
    Oak: 3,
    Intensity: 3,
    Tannin: 2,
    Fruit: 3,
  },
  fruity: {
    ResidualSugar: 2,
    Body: 3,
    Acidity: 3,
    Oak: 3,
    Intensity: 4,
    Tannin: 3,
    Fruit: 5,
  },
  funky: {
    ResidualSugar: 1,
    Body: 3,
    Acidity: 3,
    Oak: 3,
    Intensity: 5,
    Tannin: 3,
    Fruit: 2,
  },
  light: {
    ResidualSugar: 1,
    Body: 2,
    Acidity: 4,
    Oak: 2,
    Intensity: 3,
    Tannin: 1,
    Fruit: 3,
  },
  medium: {
    ResidualSugar: 1,
    Body: 3,
    Acidity: 3,
    Oak: 3,
    Intensity: 3,
    Tannin: 2,
    Fruit: 3,
  },
  minerally: {
    ResidualSugar: 2,
    Body: 3,
    Acidity: 4,
    Oak: 1,
    Intensity: 3,
    Tannin: 2,
    Fruit: 1,
  },
  'not tannic': {
    ResidualSugar: 3,
    Body: 3,
    Acidity: 3,
    Oak: 2,
    Intensity: 3,
    Tannin: 1,
    Fruit: 3,
  },
  oaked: {
    ResidualSugar: 3,
    Body: 3,
    Acidity: 3,
    Oak: 5,
    Intensity: 3,
    Tannin: 3,
    Fruit: 3,
  },
  rustic: {
    ResidualSugar: 1,
    Body: 3,
    Acidity: 4,
    Oak: 2,
    Intensity: 4,
    Tannin: 2,
    Fruit: 2,
  },
  smooth: {
    ResidualSugar: 2,
    Body: 5,
    Acidity: 2,
    Oak: 4,
    Intensity: 3,
    Tannin: 2,
    Fruit: 4,
  },
  sweetness: {
    ResidualSugar: 4,
    Body: 4,
    Acidity: 2,
    Oak: 2,
    Intensity: 4,
    Tannin: 2,
    Fruit: 5,
  },
  unoaked: {
    ResidualSugar: 3,
    Body: 3,
    Acidity: 3,
    Oak: 1,
    Intensity: 3,
    Tannin: 3,
    Fruit: 3,
  },
};
